# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='\u4e3b\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5168\u6587')),
                ('source_site', models.CharField(max_length=255, verbose_name='\u6765\u6e90\u7ad9')),
                ('source_url', models.CharField(max_length=255, verbose_name='\u6765\u6e90URL')),
                ('tag', models.CharField(max_length=255, verbose_name='\u6807\u7b7e')),
                ('keywords', models.CharField(max_length=255, verbose_name='\u5173\u952e\u8bcd')),
                ('page_date', models.CharField(max_length=255, verbose_name='\u65e5\u671f')),
            ],
        ),
    ]
