# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gov_msg',
            name='float_date',
            field=models.FloatField(max_length=255, null=True, verbose_name='\u65f6\u95f4\u6233'),
        ),
    ]
