# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180227_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.IntegerField(default=0, verbose_name='\u8bc4\u5206'),
        ),
    ]
